import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  max: {
    flex: 1,
  },
  buttonHolder: {
    height: 100,
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  button: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    backgroundColor: '#0093E9',
    borderRadius: 25,
  },
  buttonText: {
    color: '#fff',
  },
  fullView: {
    width: '100%',
    height: '100%',
  },
  minView: {
    width: 134,
    height: 192,
  },
  minContainer: {
    position: 'absolute',
    bottom: 250,
    right: 0,
    padding: 0,
    margin: 0,
    height: 192,
  },
  Controls: {
    position: 'absolute',
    bottom: 25,
    left: 0,
    width: '100%',
    height: 70,
    zIndex: 10,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  minOverlay: {
    ...(StyleSheet.absoluteFill as object),
    backgroundColor: 'black',
    opacity: 0.7,
    height: '100%',
  },
  minCloseBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.1)',
    width: 46,
    height: 46,
    borderRadius: 23,
    position: 'absolute',
    right: 5,
    top: 5,
  },
  controlBtn: {
    width: 46,
    height: 46,
    backgroundColor: 'rgba(0,0,0,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  leftRemoteBtn: {
    borderTopLeftRadius: 23,
    borderBottomLeftRadius: 23,
    borderRightWidth: 4 * StyleSheet.hairlineWidth,
    borderColor: '#fff',
  },
  rightRemoteBtn: {
    borderTopRightRadius: 23,
    borderBottomRightRadius: 23,
    borderLeftWidth: 4 * StyleSheet.hairlineWidth,
    borderColor: '#fff',
  },
  remoteBtnContainer: {
    width: '100%',
    display: 'flex',
    // marginVertical: '25%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignSelf: 'center',
    height: '100%',
    alignItems: 'center',
  },
  localBtn: {
    borderRadius: 23,
    borderWidth: 4 * StyleSheet.hairlineWidth,
    borderColor: '#007aff',
    backgroundColor: '#007aff',
  },
  endCall: {
    borderRadius: 23,
    borderWidth: 4 * StyleSheet.hairlineWidth,
    borderColor: '#f14',
    width: 46,
    height: 46,
    backgroundColor: '#f14',
  },
  iconButtonA: {
    backgroundColor: '#3b4653',
    padding: 12,
    borderRadius: 50,
  },
  iconButtonB: {
    width: 150,
    backgroundColor: '#3b4553',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    flexDirection: 'row',
    gap: 10,
    marginTop: 22,
    marginBottom: 10,
  }
});
